version: '3.8'

services:
  # MongoDB for real-time operations
  mongodb:
    image: mongo:7.0
    container_name: remote-jobs-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: remote_jobs_platform
    volumes:
      - mongodb_data:/data/db
      - ./backend/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    networks:
      - remote-jobs-network

  # MinIO for data lake (S3-compatible)
  minio:
    image: minio/minio:latest
    container_name: remote-jobs-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - remote-jobs-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: remote-jobs-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - remote-jobs-network

  # PostgreSQL for data warehouse (optional)
  postgres:
    image: postgres:15-alpine
    container_name: remote-jobs-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: remote_jobs_warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - remote-jobs-network

  # MongoDB Express for database management
  mongo-express:
    image: mongo-express:latest
    container_name: remote-jobs-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - remote-jobs-network

volumes:
  mongodb_data:
  minio_data:
  redis_data:
  postgres_data:

networks:
  remote-jobs-network:
    driver: bridge
